export const designsData = [
  {
    id: 1,
    slug: "modern-luxury-living-room",
    title: "Modern Luxury Living Room",
    category: "Living Room",
    coverImage: "/projectsImg/forest-edge/fe-img2.webp",
    description: "A luxurious living room concept combining warm textures, elegant lighting, premium materials, and timeless architectural styling.",
    longDescription: "This design focuses on creating a calm and sophisticated atmosphere using layered textures, soft neutral tones, and modern furniture compositions. Large windows and ambient lighting enhance openness and visual comfort.",
    features: [
      "Premium marble finishes",
      "Warm ambient lighting",
      "Minimal luxury styling",
      "Custom furniture concepts",
      "Natural textures and tones",
    ],
    images: [
      "/projectsImg/forest-edge/fe-img2.webp",
      "/projectsImg/etna/sr-img4.webp",
      "/projectsImg/varaprasad/vp-img1.png",
      "/projectsImg/kollur/kl-img1.webp",
    ],
  },
  {
    id: 2,
    slug: "minimal-bedroom-design",
    title: "Minimal Bedroom Design",
    category: "Bedroom",
    coverImage: "/projectsImg/kollur/kl-img10.webp",
    description: "Minimal bedroom interiors crafted for comfort, elegance, and modern simplicity.",
    longDescription: "A calming bedroom design concept using soft materials, subtle lighting, and clean geometry to create a peaceful and luxurious retreat.",
    features: [
      "Soft layered lighting",
      "Wood texture detailing",
      "Minimal decor styling",
      "Luxury bed composition",
      "Neutral calming palette",
    ],
    images: [
      "/projectsImg/kollur/kl-img8.webp",
      "/projectsImg/kollur/kl-img9.webp",
      "/projectsImg/etna/sr-img3.webp",
      "/projectsIm/etna/sr-img12.webp",
    ],
  },
  {
    id: 3,
    slug: "contemporary-kitchen-design",
    title: "Contemporary Kitchen Design",
    category: "Kitchen",
    coverImage: "/projectsImg/etna/sr-img16.webp",
    description: "A clean and functional kitchen concept designed with premium modern aesthetics.",
    longDescription: "This contemporary kitchen combines intelligent space planning with elegant materials, creating a sophisticated culinary environment. Featuring hidden storage and sleek, handleless cabinetry.",
    features: [
      "Matte finish cabinetry",
      "Premium countertop styling",
      "Integrated lighting",
      "Functional luxury layout",
      "Modern storage concepts",
    ],
    images: [
      "/projectsImg/forest-edge/fe-img6.webp",
      "/projectsImg/kollur/kl-img3.webp",
      "/projectsImg/kollur/kl-img5.webp",
      "/projectsImg/kollur/kl-img6.webp",
      "/projectsImg/kollur/kl-img7.webp"
    ],
  },

];