export interface Project {
  id: number;
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  heroImage: string;
  gallery: string[];
  projectDetails: string;
  client: string;
  location: string;
  houseType: string;
  year: string;
  bg: string;
  textColor: string;
}

const FALLBACK_HERO =
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop";

const FALLBACK_GALLERY = [
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop",
];

export const projectsData: Project[] = [
  {
    id: 1,
    slug: "forest-edge",
    title: "Forest Edge Residence",
    shortDescription: "Luxury contemporary residence with elegant interiors.",
    description: "A premium villa designed with timeless interiors and functional spaces.",
    heroImage: "/projectsImg/forest-edge/fe-img7.JPG",
    gallery: Array.from({ length: 16 }, (_, i) => `/projectsImg/forest-edge/fe-img${i + 1}.JPG`),
    projectDetails: "Premium residential interior project.",
    client: "Private Residence",
    location: "Hyderabad",
    houseType: "Luxury Villa",
    year: "2025",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 2,
    slug: "rajapushpa-provincia",
    title: "Rajapushpa Provincia",
    shortDescription: "Luxury apartment interiors with premium finishes.",
    description: "Modern elegant interiors crafted for luxurious living.",
    heroImage: "/projectsImg/rajapushpa/rp-img5.JPG",
    gallery: Array.from({ length: 40 }, (_, i) => `/projectsImg/rajapushpa/rp-img${i + 1}.JPG`),
    projectDetails: "Complete luxury apartment interior.",
    client: "Private Residence",
    location: "Rajapushpa Provincia",
    houseType: "Luxury Apartment",
    year: "2025",
    bg: "#3A393F",
    textColor: "#F4EDDB",
  },
  {
    id: 3,
    slug: "luxury-villa",
    title: "Luxury Villa",
    shortDescription: "Bespoke villa interiors with timeless elegance.",
    description: "Premium villa with custom-designed luxury interiors.",
    heroImage: "/projectsImg/villa/villa-img1.JPG",
    gallery: Array.from({ length: 55 }, (_, i) => `/projectsImg/villa/villa-img${i + 1}.JPG`),
    projectDetails: "Luxury villa featuring premium materials and bespoke furniture.",
    client: "Private Villa",
    location: "Hyderabad",
    houseType: "Luxury Villa",
    year: "2025",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 4,
    slug: "bhargavi-vaishnavi-oasis",
    title: "Bhargavi – Vaishnavi Oasis",
    shortDescription: "We created a beautiful vibrant oasis for her 2 BHK apartment.",
    description: "The design seamlessly blends refreshing tones with comfortable spaces.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Modern 2BHK interiors.",
    client: "Bhargavi",
    location: "Vaishnavi Oasis",
    houseType: "2BHK",
    year: "2019",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 5,
    slug: "praveen-aparna-zenith",
    title: "Praveen – Aparna Zenith",
    shortDescription: "Luxury 3BHK apartment.",
    description: "Modern interiors balancing style and practicality.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Luxury apartment.",
    client: "Praveen",
    location: "Nallagandla",
    houseType: "3BHK",
    year: "2024",
    bg: "#3A393F",
    textColor: "#F4EDDB",
  },
  {
    id: 6,
    slug: "kunjal-darshan-botanika",
    title: "Kunjal & Darshan – The Botanika",
    shortDescription: "Modern 3BHK redesign.",
    description: "Smart layouts with contemporary styling.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Modern residence.",
    client: "Kunjal & Darshan",
    location: "Gachibowli",
    houseType: "3BHK",
    year: "2024",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 7,
    slug: "sammys-villa-bangalore",
    title: "Sammy's Villa – Bangalore",
    shortDescription: "Luxury villa interiors.",
    description: "Elegant and sophisticated villa.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Luxury villa.",
    client: "Sammy's Villa",
    location: "Bangalore",
    houseType: "Villa",
    year: "2024",
    bg: "#3A393F",
    textColor: "#F4EDDB",
  },
  {
    id: 8,
    slug: "haseeb-my-home-bhooja",
    title: "Haseeb – My Home Bhooja",
    shortDescription: "Luxury 4BHK apartment.",
    description: "Dynamic luxury styling.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Luxury residence.",
    client: "Haseeb Mohammed",
    location: "Raidurg",
    houseType: "4BHK",
    year: "2023",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 9,
    slug: "indrani-my-home-krishe",
    title: "Indrani – My Home Krishe",
    shortDescription: "Bright and airy interiors.",
    description: "Natural light focused design.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Elegant home.",
    client: "Indrani",
    location: "Gachibowli",
    houseType: "3BHK",
    year: "2022",
    bg: "#3A393F",
    textColor: "#F4EDDB",
  },
  {
    id: 10,
    slug: "rakesh-bhupathi-nagole",
    title: "Rakesh Bhupathi – Nagole",
    shortDescription: "Contemporary 4BHK.",
    description: "Elegant modern living.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Modern residence.",
    client: "Rakesh Bhupathi",
    location: "Nagole",
    houseType: "4BHK",
    year: "2022",
    bg: "#F4EDDB",
    textColor: "#3A393F",
  },
  {
    id: 11,
    slug: "mr-nageswara-rao",
    title: "Mr. Nageswara Rao",
    shortDescription: "Modern smart home.",
    description: "Smart and functional interiors.",
    heroImage: FALLBACK_HERO,
    gallery: FALLBACK_GALLERY,
    projectDetails: "Smart home project.",
    client: "Mr. Nageswara Rao",
    location: "Madhapur",
    houseType: "3BHK",
    year: "2022",
    bg: "#3A393F",
    textColor: "#F4EDDB",
  },
];